# Generated by Django 2.2.11 on 2020-03-22 22:25

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_localize.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtail_localize', '0006_delete_language_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_source_translation', models.BooleanField(default=True)),
                ('body', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(features=['h2', 'bold', 'italic', 'link']))])),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(wagtail_localize.models.TranslatablePageRoutingMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_source_translation', models.BooleanField(default=True)),
                ('layout', models.CharField(choices=[('col1', '1 Col')], default='col1', max_length=20, verbose_name='Layout')),
                ('body', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('text', wagtail.core.blocks.RichTextBlock(features=['h2', 'bold', 'italic', 'ul', 'ol', 'link', 'image', 'document-link']))])),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
